services:
  db:
    image: postgres:15
    container_name: subscription_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: subscription_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
